### PR TITLE
fix: missing random stub in accepted values list

### PR DESCRIPTION
**Pull request by 8ctopus**

### CODE REVIEW

**Comment by jfcherng** [comment]
I am not sure whether there are more valid values. Could you copy them from https://github.com/bmewburn/vscode-intelephense/blob/d9f9da554e3441cfcc5139f63765f3e60e31acf8/package.json#L169-L355 ? Thanks.

**Comment by 8ctopus** [comment]
I did so that's how I found the missing one.

**Comment by jfcherng** [comment]
Thanks.

**Comment by 8ctopus** [comment]
You're welcome! Great plugin, I use it all the time as I'm a sublime fan.

**Pull request merged**
